### ISSUE TITLE
Plugin exits in init: "Error: This callback function has already been called by someone else; it can only be called one time."

### ISSUE THREAD

**Issue by jvosswi** [jortgies/homebridge-rademacher-blinds#2]
During initialization phase, the plugin exits with "Error: This callback function has already been called by someone else; it can only be called one time."

homebridge with: 
"homebridge-rademacher-blinds" (v0.0.5), 
"homebridge-homematic" (v0.0.66)

_pi@obh-raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-02-20 00:36:44] Loaded plugin: homebridge-homematic
[2017-02-20 00:36:44] Registering platform 'homebridge-homematic.HomeMatic'
[2017-02-20 00:36:44] ---
[2017-02-20 00:36:45] Loaded plugin: homebridge-rademacher-blinds
[2017-02-20 00:36:45] Registering platform 'homebridge-rademacher-blinds.RademacherBlinds'
[2017-02-20 00:36:45] ---
[2017-02-20 00:36:45] Loaded config.json with 0 accessories and 2 platforms.
[2017-02-20 00:36:45] ---
[2017-02-20 00:36:45] Loading 2 platforms...
[2017-02-20 00:36:45] [RademacherBlinds] Initializing RademacherBlinds platform...
RademacherBlinds init
[2017-02-20 00:36:45] [HomeMatic CCU] Initializing HomeMatic platform...
[2017-02-20 00:36:45] [HomeMatic CCU] Homematic Plugin Version 0.0.66
[2017-02-20 00:36:45] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[2017-02-20 00:36:45] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[2017-02-20 00:36:45] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2017-02-20 00:36:45] [HomeMatic CCU] init RPC for 0
[2017-02-20 00:36:45] [HomeMatic CCU] Fetching Homematic devices...
[2017-02-20 00:36:45] Loading 0 accessories...
[2017-02-20 00:36:45] [HomeMatic CCU] XML-RPC server for interface BidCos-RF. is listening on port 9090.
[2017-02-20 00:36:45] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[2017-02-20 00:36:45] [RademacherBlinds] Found: Rollo Esszimmer - Blind Essz [40]
[2017-02-20 00:36:45] [RademacherBlinds] Online: undefined [40]
[2017-02-20 00:36:45] [RademacherBlinds] Blind Essz - Setting target position: 62
[2017-02-20 00:36:45] [RademacherBlinds] Online: undefined [40]
[2017-02-20 00:36:45] [RademacherBlinds] Blind Essz - Setting target position: 47
[2017-02-20 00:36:45] [RademacherBlinds] Blind Essz - Setting target position: 47
[2017-02-20 00:36:45] [RademacherBlinds] Found: Rollo Wohnzimmer klein - Blind Wohnz kl [61]
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:145:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-rademacher-blinds/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-blinds/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-blinds/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:291:19)
pi@obh-raspberrypi:~/.homebridge $

This is the result of "<hompilot-ip>//deviceajax.do?devices=1":

{ "response" : "get_visible_devices", "status" : "ok", "devices" : [{"did":10011,"name":"Rollo Esszimmer","description":"Blind Essz","initialized":1,"position":73,"productName":"RolloTron Standard","serial":"40","statusesMap":{"Position":73,"Manuellbetrieb":0},"status_changed":1487523623,"deviceGroup":2,"iconSet":{"name":"Rollladen 2","description":"Rollladen Icon-Set mit Streben","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen2.png", "numTiles" : 5 },"k":"iconset15"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"40 84 56","visible":true,"groups" : [  ] ,"favoredId":5027,"properties":{"generic":3,"wind":3,"trigger":3,"closingContact":3,"dusk":3,"smoke":3,"sun":3,"temperature":3,"manual":3,"time":2,"dawn":3,"dust":3,"favored":0,"smartphone":3,"motion":3,"temperator":3,"warning":3,"rain":3,"states":[{"cfgKey":"setMorningAuto","cfgId":103,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0}]},"sortId":222,"sTypes":[],"version":"1.2","sync":-2147483337,"messages":[],"hasErrors":0,"autos":[3,2,0,1,4]},{"did":10010,"name":"Rollo Küche","description":"Blind Kuech","initialized":1,"position":38,"productName":"RolloTron Standard","serial":"40","statusesMap":{"Position":38,"Manuellbetrieb":0},"status_changed":1487544310,"deviceGroup":2,"iconSet":{"name":"Rollladen 2","description":"Rollladen Icon-Set mit Streben","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen2.png", "numTiles" : 5 },"k":"iconset15"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"40 76 92","visible":true,"groups" : [  ] ,"favoredId":5026,"properties":{"generic":3,"wind":3,"trigger":3,"closingContact":3,"dusk":3,"smoke":3,"sun":3,"temperature":3,"manual":3,"time":2,"dawn":3,"dust":3,"favored":0,"smartphone":3,"motion":3,"temperator":3,"warning":3,"rain":3,"states":[{"cfgKey":"setMorningAuto","cfgId":103,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0}]},"sortId":223,"sTypes":[],"version":"1.2","sync":-2147483331,"messages":[],"hasErrors":0,"autos":[3,2,0,1,4]},{"did":10008,"name":"Rollo Wohnzimmer groß","description":"Blind Wohnz gr","initialized":1,"position":53,"productName":"RolloTron Standard","serial":"40","statusesMap":{"Position":53,"Manuellbetrieb":0},"status_changed":1487523621,"deviceGroup":2,"iconSet":{"name":"Rollladen 2","description":"Rollladen Icon-Set mit Streben","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen2.png", "numTiles" : 5 },"k":"iconset15"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"40 66 AE","visible":true,"groups" : [ 5000 ] ,"favoredId":5021,"properties":{"generic":3,"wind":3,"trigger":3,"closingContact":3,"dusk":3,"smoke":3,"sun":2,"temperature":3,"manual":3,"time":2,"dawn":3,"dust":3,"favored":0,"smartphone":3,"motion":3,"temperator":3,"warning":3,"rain":3,"states":[{"cfgKey":"setMorningAuto","cfgId":103,"state":1},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":1}]},"sortId":224,"sTypes":[],"version":"1.2","sync":-2147483386,"messages":[],"hasErrors":0,"autos":[3,2,0,1,4]},{"did":10009,"name":"Rollo Wohnzimmer klein","description":"Blind Wohnz kl","initialized":1,"position":77,"productName":"RolloTron Comfort","serial":"61","statusesMap":{"Position":77,"Manuellbetrieb":0},"status_changed":1487523630,"deviceGroup":2,"iconSet":{"name":"Rollladen 2","description":"Rollladen Icon-Set mit Streben","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen2.png", "numTiles" : 5 },"k":"iconset15"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"61 76 88","visible":true,"groups" : [ 5000 ] ,"favoredId":5024,"properties":{"generic":3,"wind":3,"trigger":3,"closingContact":3,"dusk":3,"smoke":3,"sun":1,"temperature":3,"manual":3,"time":2,"dawn":3,"dust":3,"favored":0,"smartphone":3,"motion":3,"temperator":3,"warning":3,"rain":3,"states":[{"cfgKey":"setMorningAuto","cfgId":103,"state":1},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":0}]},"sortId":225,"sTypes":[30],"version":"1.2","sync":-2147483380,"messages":[],"hasErrors":0,"autos":[3,2,0,1,4]}] }

Please give support!

Kindly, jvosswi

**Comment by jortgies** [comment]
@jvosswi I just published an update, please test and report back if the problem persists.

**Comment by jvosswi** [comment]
@jortgies Unfortunately, the problem still persists.

What I did:
- stopped running homebridge
- executed "sudo npm install -g homebridge-rademacher-blinds" (just to mention: running without "sudo" terminated with errors)
-->homebridge-rademacher-blinds@0.0.6

And just to make sure:
- deleted folders "accessories" and "persist"
- rebooted

Result:

pi@obh-raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer  of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd ns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not  supported (or only supported partially) in the Apple Bonjour compatibility layer  of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd ns_sd&e=nodejs&f=DNSServiceRegister>
[2017-02-22 00:38:41] Loaded plugin: homebridge-homematic
[2017-02-22 00:38:41] Registering platform 'homebridge-homematic.HomeMatic'
[2017-02-22 00:38:41] ---
[2017-02-22 00:38:41] Loaded plugin: homebridge-rademacher-blinds
[2017-02-22 00:38:41] Registering platform 'homebridge-rademacher-blinds.Rademac herBlinds'
[2017-02-22 00:38:41] ---
[2017-02-22 00:38:41] Loaded config.json with 0 accessories and 2 platforms.
[2017-02-22 00:38:41] ---
[2017-02-22 00:38:41] Loading 2 platforms...
[2017-02-22 00:38:41] [RademacherBlinds] Initializing RademacherBlinds platform...
[2017-02-22 00:38:41] [HomeMatic CCU] Initializing HomeMatic platform...
[2017-02-22 00:38:41] [HomeMatic CCU] Homematic Plugin Version 0.0.66
[2017-02-22 00:38:41] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[2017-02-22 00:38:41] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[2017-02-22 00:38:41] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2017-02-22 00:38:41] [HomeMatic CCU] init RPC for 0
[2017-02-22 00:38:41] [HomeMatic CCU] Fetching Homematic devices...
[2017-02-22 00:38:42] Loading 0 accessories...
[2017-02-22 00:38:42] [HomeMatic CCU] XML-RPC server for interface BidCos-RF. is listening on port 9090.
[2017-02-22 00:38:42] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[2017-02-22 00:38:42] [RademacherBlinds] Found: Rollo Esszimmer - Blind Essz [40]
[2017-02-22 00:38:42] [RademacherBlinds] Online: undefined [40]
[2017-02-22 00:38:42] [RademacherBlinds] Blind Essz - Setting target position: 62
[2017-02-22 00:38:42] [RademacherBlinds] Online: undefined [40]
[2017-02-22 00:38:42] [RademacherBlinds] Blind Essz - Setting target position: 47
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at RademacherBlindsAccessory.setPositionState (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:203:5)
    at emitMany (events.js:132:20)
    at Characteristic.PositionState.emit (events.js:202:7)
    at Characteristic.PositionState.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Service.WindowCovering.Service.setCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:148:32)
    at RademacherBlindsAccessory.setTargetPosition (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:132:18)
    at emitMany (events.js:132:20)
    at Characteristic.TargetPosition.emit (events.js:202:7)
    at Characteristic.TargetPosition.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
pi@obh-raspberrypi:~/.homebridge $
